### ISSUE TITLE
ToEnv purpose

### ISSUE THREAD

**Issue by timmytofu** [dmjio/envy#2]
```
instance ToEnv PGConfig where
  toEnv = makeEnv 
       [ "PG_HOST" .= ("localhost" :: String)
       , "PG_PORT" .= (5432        :: Word16)
       , "PG_USER" .= ("user"      :: String)
       , "PG_PASS" .= ("pass"      :: String)
       , "PG_DB"   .= ("db"        :: String)
       ]
```

Why wouldn't you want toEnv to use data from the specific instance (`:: a -> EnvList a`), so that I could e.g. make `PGConfig "https://myhost" 5432 "itsme" "secretpass" "dbname"` and then output those values rather than hardcoded values for a type at large?

**Comment by dmjio** [comment]
@timmytofu, that's a good point. I think I originally had `a` as a parameter to the function in the `FromEnv` typeclass, but meant to do it on `ToEnv` instead. But you're right this would make more sense.

```haskell
------------------------------------------------------------------------------
-- | ToEnv Typeclass
class Show a => ToEnv a where
  toEnv :: a -> EnvList a
```
so then we could do
```haskell
instance ToEnv PGConfig where
  toEnv = makeEnv 
       [ "PG_HOST" .= pgHost
       , "PG_PORT" .= pgPort
       , "PG_USER" .= pgUser
       , "PG_PASS" .= pgPass
       , "PG_DB"     .= pgDb
       ]
```

If you submit a pull I can change it, otherwise I can do it sometime next week. If you submit a pull add yourself to the contributors in the cabal file.
